### ISSUE TITLE
扩展建议

### ISSUE THREAD

**Issue by yu037991** [bailinx/quick-qrcode#1]
1.识别二维码的之后建议以弹窗的方式显示出来，把识别的内容放到弹窗里，方便操作。
2.保存的二维码点击编辑之后再打开新的网站就不会再生成新的二维码了。感觉应该是个Bug。
3.历史记录中可以增加一个保存选项。（历史生成的二维码可以保存）
4.点击扩展图标生成二维码之后，扩展页面可以加个编辑功能，自定义生成的二维码尺寸。
5.点击扩展之后生成的二维码下面那个保存选项可以增加一个保存本地的功能，虽然可以通过右键保存到本地，但是直接实现这个功能比较好。
6.新建二维码这个功能，并不一定要标题和链接都得填，有的只是想把文字转成二维码，有的只想把链接转为二维码。（标题或者文字可能是必须的，链接并不是必须的）

**Comment by bailinx** [comment]
赞~  感谢给了这么多有用的建议

1. **[Accept]** 将在下个版本实现。本期已经接近完工，新增短链工具和设置页，后续设置页里将加上开关，根据个人喜好决定使用弹层或者直接copy到剪贴板

2. **[ByDesign]** 看描述应该是点击编辑后当前二维码处于激活状态，你点下这里即可关闭这种状态
![image](https://user-images.githubusercontent.com/9367897/61864515-26f79300-af04-11e9-96a9-685be54f6a62.png)

3. **[ByDesign]** 历史记录选中后，点击title位置，修改title，点击保存即可clone出另一份记录；如果修改url会更新原数据，这是隐藏的功能，后面主要功能做好后好好写下文档

4. **[Accept]** 有计划做这功能，但是本期应该来不及了，等下期看看能不能加上

5. **[Accept]** 这功能之前做了，但是考虑到不是所有人都需要，所以注释掉了，本期可以加上

6. **[ByDesign]** 标题是主键，必填。生成二维码用的是链接字段，该字段未做正则校验，可以随意填
![image](https://user-images.githubusercontent.com/9367897/61865304-928e3000-af05-11e9-874d-76f6fa8085ba.png)

不知解答是否满意？另外放一张最新的预览图

![image](https://user-images.githubusercontent.com/9367897/61865505-e862d800-af05-11e9-855e-d96e6b704855.png)

**Comment by yu037991** [comment]
> 赞~ 感谢给了这么多有用的建议
> 
> 1. **[Accept]** 将在下个版本实现。本期已经接近完工，新增短链工具和设置页，后续设置页里将加上开关，根据个人喜好决定使用弹层或者直接copy到剪贴板
> 2. **[ByDesign]** 看描述应该是点击编辑后当前二维码处于激活状态，你点下这里即可关闭这种状态
>    ![image](https://user-images.githubusercontent.com/9367897/61864515-26f79300-af04-11e9-96a9-685be54f6a62.png)
> 3. **[ByDesign]** 历史记录选中后，点击title位置，修改title，点击保存即可clone出另一份记录；如果修改url会更新原数据，这是隐藏的功能，后面主要功能做好后好好写下文档
> 4. **[Accept]** 有计划做这功能，但是本期应该来不及了，等下期看看能不能加上
> 5. **[Accept]** 这功能之前做了，但是考虑到不是所有人都需要，所以注释掉了，本期可以加上
> 6. **[ByDesign]** 标题是主键，必填。生成二维码用的是链接字段，该字段未做正则校验，可以随意填
>    ![image](https://user-images.githubusercontent.com/9367897/61865304-928e3000-af05-11e9-874d-76f6fa8085ba.png)
> 
> 不知解答是否满意？另外放一张最新的预览图
> 
> ![image](https://user-images.githubusercontent.com/9367897/61865505-e862d800-af05-11e9-855e-d96e6b704855.png)

感谢开发者的热心解答，还有几个小问题需要咨询一下。
第二点，应该是您设置的保存二维码之后自动锁定该二维码，导致打开新的网页无法生成新的二维码，感觉这里没有必要自动锁定这种操作，如果不是您提醒我还真不知道怎么解决，上次是通过卸载重新安装之后才可以继续操作的。这块儿您可以考虑一下。刚才又重新操作了一下，发现又不是自动锁定了。这块儿感觉是有点变扭。（可以去掉这个东西）
第三点我明白您的意思了，这个可以自定义，自定义之后会生成新的二维码。我说的那个意思是在这块儿加个下载到本地的选项。大概是这样
![image](https://user-images.githubusercontent.com/30470617/61867319-7db39b80-af09-11e9-82ca-4c85a42e48bd.png)
第六点那块儿，那个链接后面没必要加红色标记，给我的第一感觉就是必须要填，而且必须是链接的形式，所以那块儿可以不加那个红色标记。
新版的预览图我感觉很不错。有几个不成熟的看法，您看一下。
![image](https://user-images.githubusercontent.com/30470617/61868191-72616f80-af0b-11e9-88e6-dbb975fb3dea.png)
1.编辑页面可以单独摘到生成二维码的界面，一个大的菜单级别，在历史记录中点击某个生成的历史记录也可以进行编辑。相当于是一份大的菜单了。
2.保存那块儿可以增加一个二级菜单，保存本地的菜单。
3.那个置顶功能可以删除掉，转为手动置顶。
4.历史记录的下载功能可以单独放一个。（下载到本地，点击弹出下载框）
5.看样子新的版本您考虑是把编辑功能放到新的界面，这个我感觉很好。那么历史记录中的预览操作我感觉是可有可无的。（因为在新的页面编辑，所以预览也用不到）点击到其他历史记录时左侧会出现相应的二维码，所以，预览功能感觉有点鸡肋。
再次感谢开发者热心解答。我感觉这个扩展是我用过的二维码谷歌扩展最好用的一个扩展了。

**Comment by bailinx** [comment]
第二点我是这样考虑的，如果你需要跨Tab展示同一个二维码，就需要Pin这个功能（调试手机页面的时候经常用到）。我觉得自动Pin很方便，但是没站在用户角度考虑，本期我把这问题修掉，置顶的想法不错。 :beers:

第三点建议很好，编辑按钮是担心第一次使用不会点左侧title修改留下的。左下角下载按钮不一定能放下，应该还是会通过配置的形式自定义操作按钮。右侧历史记录卡片上，用户第一次进来默认是三个按钮`预览 - 编辑 - 删除`，后面通过配置把`下载`按钮放上去。另外空间有限，`置顶`得考虑下交互形式

第六个链接那，我改下文案再加个tips怎么样？比如叫`内容`，提示是`内容可以是链接或者文本，内容用于生成二维码，不能为空`

---
以下回答对应上文图片下五点：

1. 其实点title或者链接是可以直接编辑的，历史记录留编辑是防止新用户不知道怎么改title或者链接，所以编辑按钮不是必须但新用户要有。大菜单以简洁为主，应该只会留2个最重要的最常用操作按钮（会支持自定义），后续能放`设置页`的操作都会放到设置里页面
![image](https://user-images.githubusercontent.com/9367897/61870727-68db0600-af11-11e9-8e81-1a65b138deb2.png)

2. 我认为保存到本地还不如在历史记录加一个下载按钮更靠谱，当然为了让用户少操作一步（保存 -> 历史记录 -> 下载），我会在设置页里加上这个选项，如果你觉得下载到本地会经常用到，主操作栏就会是两个按钮：`新建`+`下载`，或者`保存`+`下载`，根据个人喜好配置

3. 自动置顶如上所说，会在本期删掉

4. 历史记录下载本期加上

5. 因为现在会自动Pin（置顶），所以加了预览（避免点击）。后续如果手动Pin的话，这功能优先级低于`Pin（置顶）`按钮，有可能会替换掉，或者作为备选功能

---
也感谢你的使用和建议。不为别的，就想把用户体验做到极致，所以你的建议很重要 :four_leaf_clover:

**Comment by yu037991** [comment]
> 第二点我是这样考虑的，如果你需要跨Tab展示同一个二维码，就需要Pin这个功能（调试手机页面的时候经常用到）。我觉得自动Pin很方便，但是没站在用户角度考虑，本期我把这问题修掉，置顶的想法不错。 🍻
> 
> 第三点建议很好，编辑按钮是担心第一次使用不会点左侧title修改留下的。左下角下载按钮不一定能放下，应该还是会通过配置的形式自定义操作按钮。右侧历史记录卡片上，用户第一次进来默认是三个按钮`预览 - 编辑 - 删除`，后面通过配置把`下载`按钮放上去。另外空间有限，`置顶`得考虑下交互形式
> 
> 第六个链接那，我改下文案再加个tips怎么样？比如叫`内容`，提示是`内容可以是链接或者文本，内容用于生成二维码，不能为空`
> 
> 以下回答对应上文图片下五点：
> 
> 1. 其实点title或者链接是可以直接编辑的，历史记录留编辑是防止新用户不知道怎么改title或者链接，所以编辑按钮不是必须但新用户要有。大菜单以简洁为主，应该只会留2个最重要的最常用操作按钮（会支持自定义），后续能放`设置页`的操作都会放到设置里页面
>    ![image](https://user-images.githubusercontent.com/9367897/61870727-68db0600-af11-11e9-8e81-1a65b138deb2.png)
> 2. 我认为保存到本地还不如在历史记录加一个下载按钮更靠谱，当然为了让用户少操作一步（保存 -> 历史记录 -> 下载），我会在设置页里加上这个选项，如果你觉得下载到本地会经常用到，主操作栏就会是两个按钮：`新建`+`下载`，或者`保存`+`下载`，根据个人喜好配置
> 3. 自动置顶如上所说，会在本期删掉
> 4. 历史记录下载本期加上
> 5. 因为现在会自动Pin（置顶），所以加了预览（避免点击）。后续如果手动Pin的话，这功能优先级低于`Pin（置顶）`按钮，有可能会替换掉，或者作为备选功能
> 
> 也感谢你的使用和建议。不为别的，就想把用户体验做到极致，所以你的建议很重要 🍀

感谢回复，我感觉您说的这个自定义非常好，毕竟并不是每个人的喜好都相同，我下午的时候没想到自定义这个东西，您这个想法感觉很赞。
您说的点击之后可以编辑我知道，编辑我感觉可以给点提示，提示用户那里是可以更改的，比如显示输入框？标红显示？再或者输入框标红显示（或者其他？）在历史记录中点击每一条历史记录的时候左侧就会提示可以修改。
提示文案那个可以改一下。内容   我感觉这个可以。
主界面可以自定义按钮，第二菜单（历史记录）中每条选项下的操作都自定义显示操作。感觉您开发可能会麻烦点。这样一来，我说的那些问题在自定义这个实现之后都是可以解决的。
以上所有的都开发好之后会非常棒。您要不要考虑在这些功能开发完毕之后加点其他东西，比如美化之类的。加点其他东西。最后再赞一下您的那个自定义！

**Comment by bailinx** [comment]
第一次进来的时候可以给点提示，给个红框之类的，具体时间我得再看一下，先做最紧要的事情。

下一期我会在工坊里做一些小工具，比如二维码美化，二维码识别。到时应该能覆盖大部分二维码的使用场景

**Comment by bailinx** [comment]
你的建议大部分已经实现，2.0 版本已经提交审核，敬请期待 ：）

![image](https://user-images.githubusercontent.com/9367897/61997348-f154d480-b0d2-11e9-8314-ad92d83cc605.png)

![image](https://user-images.githubusercontent.com/9367897/61997361-206b4600-b0d3-11e9-9ecc-e2e253a99cb3.png)

**Comment by bailinx** [comment]
已经全部实现
