### ISSUE TITLE
devtools 中，提示无法加载 jquery.min.map

### ISSUE THREAD

**Issue by ghost** [bailinx/quick-qrcode#13]
虽然不影响使用，但是有点影响开发体验哦。希望可以修复，谢谢。

![image](https://user-images.githubusercontent.com/30150098/104812534-e26d5f00-583d-11eb-99c5-5d853e640560.png)

**Comment by bailinx** [comment]
非常抱歉，这是截屏所需要的jQuery底部包含了sourcemap信息，已经删除。请升级到3.4.1版本，chrome edge均可

**Comment by ghost** [comment]
感谢
