### ISSUE TITLE
[Feature Request] 生成二维码预览完整内容

### ISSUE THREAD

**Issue by entr0pia** [bailinx/quick-qrcode#15]
![image](https://user-images.githubusercontent.com/30486766/134102461-02380734-2b36-444b-bf7e-cfbf8c7ce206.png)

**Comment by bailinx** [comment]
收到，原先这里是有多个二维码的列表，所以做了省略号。我把这里改下，另外我在想这里如果可编辑是不是更好一点？

**Comment by entr0pia** [comment]
可编辑确实会更好

**Comment by bailinx** [comment]
![image](https://user-images.githubusercontent.com/9367897/138416018-a1713ed6-5a6b-4aec-87e2-68792ee80543.png)

3.6.0版本已经支持该功能了哦，只是暂时无法编辑
