### ISSUE TITLE
希望能换个图标

### ISSUE THREAD

**Issue by jk3068** [bailinx/quick-qrcode#2]
插件很不错，界面也很好看，唯一不太满意的地方就是图标在无痕模式下显得不太好看，图片中第一个插件的图标就相对好一点，希望能换个图标，感谢。
![20190816163119](https://user-images.githubusercontent.com/54171137/63157275-235db480-c049-11e9-8094-4b14199907e5.png)
图片中第一个插件是[极简二维码](https://chrome.google.com/webstore/detail/极简二维码/kjohkapghefjgieikhbhokojmkhejlel)。

**Comment by bailinx** [comment]
很好的建议。这次迭代换图标 :grinning:

**Comment by bailinx** [comment]
我也一直在想图标的事情，千篇一律的二维码图标能否来点不一样的

**Comment by bailinx** [comment]
v2.1.0版本已提交审核，新特性如下：

1. 新增新手引导，让您快速了解插件
2. 新增技术白皮书，详细讲述了插件运行机制
3. 新增操作提示，点击按钮后会toast提醒
4. 优化赞赏页，更简单明了
5. 更换主题图标，希望您能喜欢

**Comment by jk3068** [comment]
新图标挺不错的，感谢。

**Comment by bailinx** [comment]
:grin: 感谢你的使用
