### ISSUE TITLE
显示 bug

### ISSUE THREAD

**Issue by jk3068** [bailinx/quick-qrcode#3]
比如在[这个网站](https://lhammer.cn/You-need-to-know-css/#/zh-cn/inner-rounding)，通过右键菜单生成二维码，会在`iframe`元素中的`body`插入同样的节点，似乎将`manifest.json`文件里的`all_frames`改为`false`可以解决，但不知道是否会造成其他 bug，希望您能看一下。
```
"content_scripts": [
    {
        "all_frames": false
    }
]
```
![20190819132628](https://user-images.githubusercontent.com/54171137/63241087-fc8bc200-c284-11e9-99e0-2c17ad81ff47.png)

**Comment by jk3068** [comment]
顺便反馈一个错字，`纪录`应为`记录`。
![20190819144024](https://user-images.githubusercontent.com/54171137/63244337-b12ae100-c28f-11e9-8837-d9e8ea9286dd.png)

**Comment by bailinx** [comment]
收到，问题确实存在，下个小版本修复

**Comment by bailinx** [comment]
问题在 **v2.1.1** 版本修复，chrome应用商店**v2.1.0**还在审核中，估计还得一两天时间；如果是通过离线包安装，等待浏览器自动更新即可。

感谢你的支持，我可以在插件里加上你的github名称和链接，如果你想要的话 ：）

**Comment by jk3068** [comment]
感谢修复，加名称就不必了，这只是随便注册的账号而已。

**Comment by bailinx** [comment]
:grin: :grin::grin: 哈哈，好的。下一个版本会做二维码美化，敬请期待
