### ISSUE TITLE
Pin 状态异常

### ISSUE THREAD

**Issue by jk3068** [bailinx/quick-qrcode#4]
1. 点击`编辑`后，`Pin`和右上角会变为选中状态，实际上并未激活 Pin 模式，重新打开弹出框后又恢复未选中状态。
2. 点击`编辑`，然后多次点击`Pin`会出现弹出`固定成功`，但其实并未固定，`Pin`和右上角也是未选中状态。（这个现象并不是一定会出现，出现原因不明，另外动图前面有一段是多余的，请无视）
![GIF](https://user-images.githubusercontent.com/54171137/63687769-0f2f6980-c838-11e9-9ae6-29be222e36e7.gif)

**Comment by bailinx** [comment]
收到，改Pin的时候编辑确实没测到，应该还走的老逻辑。我尽快修复

**Comment by bailinx** [comment]
您好，问题1已经修复，问题2没复现，可能是由于问题一导致的

---
版本 v2.1.2 已经提交审核，改动如下：

1. 新增`设置 - 弹出层 - 开启Pin的操作提示`，点击后可关闭“固定成功”的提示（避免骚扰）。默认开启
2. 新增新用户统计埋点
3. 修复点击编辑后Pin状态异常
4. 优化`Pin`按钮的点击体验，点击一次即可切换


![image](https://user-images.githubusercontent.com/9367897/63874869-ea342580-c9f4-11e9-8283-0596bdeb5baf.png)


极简模式

![image](https://user-images.githubusercontent.com/9367897/63874924-089a2100-c9f5-11e9-8171-8875d05890a1.png)

离线包地址（也可以等chrome商店更新）
https://cdn.66tools.com/extension/chrome_qrcode-2.1.2-chrome.crx

**Comment by jk3068** [comment]
感谢修复。
