### ISSUE TITLE
全网征集插件名称

### ISSUE THREAD

**Issue by bailinx** [bailinx/quick-qrcode#5]
插件从无到有经过很多版本迭代，已经比较成熟。

现想征集一个比较有创意且小清新的名称，

有思路的同学在下方留言~

关键字：二维码、蓝色、深蓝

---

Plug-ins have been iterated from many versions and have matured.

I want to collect a more creative and small fresh name.

Students with ideas are leaving a message below~

Keywords: QR code, blue, dark blue

**Comment by s0tgcxyz** [comment]
根据图标和关键字感觉可以叫`BlueQ`:smile:，这样可能就不利于搜索，也可以像[这个插件](https://chrome.google.com/webstore/detail/amino-live-css-editor/pbcpfbcibpcbfbmddogfhcijfpboeaaf)一样标题叫`BlueQ：二维码生成和解析插件`右键菜单还是`BlueQ`，脑洞有限，想不出好的名称，只能给个思路:joy:。

**Comment by bailinx** [comment]
> 根据图标和关键字感觉可以叫`BlueQ`😄，这样可能就不利于搜索，也可以像[这个插件](https://chrome.google.com/webstore/detail/amino-live-css-editor/pbcpfbcibpcbfbmddogfhcijfpboeaaf)一样标题叫`BlueQ：二维码生成和解析插件`右键菜单还是`BlueQ`，脑洞有限，想不出好的名称，只能给个思路😂。

哈哈，`BlueQQ`既视感，隐藏这么深的issue都找到了。我再想想，这事也不急。顺便问下，老铁，你从啥时候使用这款插件的

**Comment by s0tgcxyz** [comment]
我就是提另几个 Issue 的那个，那个账号忘了😂，差不多是提第一个 Issue 前不久开始用的。这个 Issue 一开始就看见了的，因为账号原因就没来回复😂。

**Comment by bailinx** [comment]
> 我就是提另几个 Issue 的那个，那个账号忘了😂，差不多是提第一个 Issue 前不久开始用的。这个 Issue 一开始就看见了的，因为账号原因就没来回复😂。

哈哈哈，看来是铁粉无疑了。 可以加QQ群吹水哦
