### ISSUE TITLE
[问题反馈] 插件影响了页面样式

### ISSUE THREAD

**Issue by huangjunjia** [bailinx/quick-qrcode#9]
# 问题反馈

开启插件之后，会导致部分页面样式失效，如google首页

- 开启插件之后

![image](https://user-images.githubusercontent.com/19429582/84612311-d6f63600-aef2-11ea-9637-1a34cee85f92.png)

- 关闭插件之后

![image](https://user-images.githubusercontent.com/19429582/84612330-ebd2c980-aef2-11ea-81d6-be79c715e43a.png)

希望能尽快修复

**Comment by KangSpace** [comment]
🔝+1 ，新版本更新后，  影响了其他网站本身的样式 。

**Comment by bailinx** [comment]
非常抱歉，新版本已经提交审核。可以先用edge插件代替，或者暂时停用

**Comment by bailinx** [comment]
@KangSpace @HuangJunjia  审核已经通过，请更新至v3.1.1版本
